# version: '3'

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=http://localhost:8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=bookstack_password
      - DB_DATABASE=bookstackapp
    volumes:
      - ./bookstack_data:/config
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack_password
    volumes:
      - ./mysql_data:/config
    ports:
      - "3306:3306"  # Exposes port 3306 on the host
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

  mysql_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    environment:
      - DATA_SOURCE_NAME=bookstack:bookstack_password@(db:3306)/
    ports:
      - "9104:9104"
    depends_on:
      - db
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  bookstack_data:
  mysql_data:


# The provided docker-compose.yml file defines a multi-container environment using Docker Compose. Each block of code specifies a 
# service, its configuration, and how it interacts with other services. Here's a short explanation of each service and its role.

# Prometheus is an open-source monitoring and alerting system that collects metrics
# from configured targets at given intervals, evaluates rule expressions, displays
# results, and can trigger alerts when specified conditions are observed. It is
# designed for reliability and is used to monitor highly dynamic service-oriented
# architectures and hardware.

# Grafana is an open-source analytics and interactive visualization web application
# that allows users to create dashboards and graphs for monitoring various data sources.
# It supports multiple data sources and can produce charts, graphs, and alerts for the web.

# BookStack is a free and open-source wiki software designed to be simple, self-hosted,
# and easy to use. It is built on the Laravel PHP framework and allows users to organize
# and store information in a structured manner using books, chapters, and pages.

# MariaDB is an open-source relational database management system (RDBMS) that originated as a fork of MySQL. It was developed by the # original creators of MySQL due to concerns over MySQL's acquisition by Oracle Corporation. MariaDB is designed to remain free and 
# open-source under the GNU General Public License (GPL).

# mysqld_exporter is a Prometheus exporter for MariDB/MySQL server metrics. It collects and
# exposes MariaDB server metrics to Prometheus, allowing for monitoring and alerting
# on the performance and health of MariaDB databases.

# node_exporter is a Prometheus exporter that collects and exposes hardware and 
# OS-level metrics from *NIX systems. It provides system-level insights such as 
# CPU usage, memory, disk I/O, and network statistics, which can be scraped by 
# Prometheus for monitoring and alerting purposes.
