global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # Node Exporter listens on port 9100 by default
  
  - job_name: 'bookstack'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bookstack:80']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']