global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bookstack'
    static_configs:
      - targets: ['bookstack:80']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
